package:
  name: statsmodels
  version: 0.10.1

source:
  url: https://files.pythonhosted.org/packages/d3/7d/4f1f18ad782d6b913aeff17d553859fed40751ecf15ef698c69811e622e6/statsmodels-0.10.1.tar.gz
  sha256: 320659a80f916c2edf9dfbe83512d9004bb562b72eedb7d9374562038697fa10

  patches:
    - patches/add-emscripten-cpu.patch
    - patches/disable-maybe-uninitialized.patch
    - patches/dont-include-execinfo.patch
    - patches/fix-longdouble.patch
    - patches/fix-static-init-of-nditer-pywrap.patch
    - patches/force_malloc.patch
    - patches/init-alloc-cache.patch
    - patches/use-local-blas-lapack.patch
    - patches/fix-install-with-skip-build.patch

build:
  skip_host: False
  cflags: -include math.h -I../../config


test:
  imports:
    - statsmodels
