package:
  name: statsmodels
  version: 0.10.1

source:
  url: https://files.pythonhosted.org/packages/d3/7d/4f1f18ad782d6b913aeff17d553859fed40751ecf15ef698c69811e622e6/statsmodels-0.10.1.tar.gz
  sha256: 320659a80f916c2edf9dfbe83512d9004bb562b72eedb7d9374562038697fa10


requirements:
  run:
    - numpy
    - scipy
    - pandas
    - patsy

test:
  imports:
    - statsmodels

